# D:\Microservice-Project\config-repo\api-gateway.yml

server:
  port: 9191 # Cổng mà API Gateway sẽ chạy

# Cấu hình Eureka client cho Gateway
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Cấu hình định tuyến (routes) cho Gateway
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1  # bỏ /catalog trước khi forward đến catalog-service
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    reactor.netty.http.client: DEBUG