# D:\Microservice-Project\config-repo\api-gateway.yml

server:
  port: 9191 # Cổng mà API Gateway sẽ chạy

# Cấu hình Eureka client cho Gateway
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter
            - name: LoggingFilter

        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter
            - name: LoggingFilter

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter
              args: {}
            - name: LoggingFilter
              args: {}

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1
            - name: JwtAuthenticationFilter
            - name: LoggingFilter

      default-filters:
        - PreserveHostHeader
logging:
  level:
    org.example.apigateway.filter: DEBUG
    org.springframework.security: DEBUG
    org.springframework.cloud.gateway: TRACE