# D:\Microservice-Project\config-repo\auth-service.yml

server:
  port: 9192

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1522/XEPDB1
    username: AUTH_USER
    password: AUTH_USER
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka