# D:\Microservice-Project\config-repo\cart-service.yml

server:
  port: 0

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cart-db
    redis:
      host: localhost
      port: 6379


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka