# D:\Microservice-Project\config-repo\cart-service.yml

server:
  port: 0

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cart-db
    redis:
      host: localhost
      port: 6379

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: https://my-auth-server.com
jwt:
  secret: bXktc3VwZXItc2VjdXJlLWtleS1oZXJlLXNob3VsZC1iZS1sb25nLWVuYWY
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka