# D:\Microservice-Project\config-repo\order-service.yml

server:
  port: 0

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1522/XEPDB1
    username: ORDER_DB
    password: ORDER_DB
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
security:
  oauth2:
    resourceserver:
      jwt:
        # Chỉ cần cung cấp issuer-uri, Spring sẽ tự cấu hình phần còn lại
        # URI này chỉ là định danh, không nhất thiết phải gọi được
        issuer-uri: https://my-auth-server.com
jwt:
  secret: bXktc3VwZXItc2VjdXJlLWtleS1oZXJlLXNob3VsZC1iZS1sb25nLWVuYWY