# D:\Microservice-Project\config-repo\payment-service.yml

server:
  port: 0

spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1522/XEPDB1
    username: PAYMENT_DB
    password: PAYMENT_DB
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  circuitbreaker:
    enabled: true
security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: https://my-auth-server.com
jwt:
  secret: bXktc3VwZXItc2VjdXJlLWtleS1oZXJlLXNob3VsZC1iZS1sb25nLWVuYWY

resilience4j:
  circuitbreaker:
    instances:
      orderServiceFeignClient:
        slidingWindowSize: 10              # Số request gần nhất để thống kê lỗi
        minimumNumberOfCalls: 5            # Số request tối thiểu để bắt đầu tính toán
        failureRateThreshold: 50           # 50% lỗi thì mở circuit
        waitDurationInOpenState: 10s       # Mở circuit 10s rồi thử lại
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true