# D:\Microservice-Project\config-server\application.yml
server:
  port: 8888

#spring:
#  application:
#    name: config-server
#  profiles:
#    active: jdbc
#  datasource:
#    url: jdbc:oracle:thin:@//localhost:1522/XEPDB1
#    username: PROPERTIES
#    password: PROPERTIES
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#  cloud:
#    config:
#      server:
#        jdbc:
#          sql: >
#            SELECT PROPERTY_KEY, PROPERTY_VALUE
#            FROM PROPERTIES
#            WHERE APPLICATION = ? AND PROFILE = ? AND LABEL = ?
#          default-label: main
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/giakhanh102003/Microservice-Project.git
          clone-on-start: true
          search-paths: config-repo
